# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
require 'dotenv'

# .envファイルを読み込む
Dotenv.load(File.join(__dir__, '..', '.env'))
# Flutter SDK に関連するコードをインクルード
ENV['FLUTTER_ROOT'] ||= '/Users/haruna/development/flutter'
load File.join(ENV['FLUTTER_ROOT'], 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  # Uncomment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Flutter 用の Pod をインストール
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
